### ISSUE TITLE
Remove duplicate names of chess players

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-data#17]
The demo database available at https://chesslablab.com contains more than 500,000 games available for study for free.

However, names of chess players may be duplicated and are sometimes unclear.

![figure-01](https://user-images.githubusercontent.com/4062000/212470557-a759c9c0-e0bf-4e32-b219-2aa94523df6a.png)
**Figure 1**. Viswanathan Anand?

![figure-02](https://user-images.githubusercontent.com/4062000/212470565-da220931-0173-46b5-861c-778b4368cbcf.png)
**Figure 2**. Zsuzsa Polgár?

![figure-03](https://user-images.githubusercontent.com/4062000/212470570-3494b178-63cc-496c-a783-d560926ca702.png)
**Figure 3**. Gary Kasparov?

Find out a way to be more specific about searching games by player name and remove duplicates so that searching data will be easier.

Keep it up, and happy coding and learning!

**Comment by franbonafina** [comment]
@franbonafina take a look of this.
They're using Rubix ML for PHP.

**Comment by CodeMaster7000** [comment]
Hi there, happy learning and coding!

**Comment by franbonafina** [comment]
@CodeMaster7000 What API URL are you using ?

**Comment by programarivm** [comment]
@franbonafina the API is being documented with examples at [Chess API for Web Apps](https://chess-api.readthedocs.io/en/latest/).

**Comment by programarivm** [comment]
Closed this issue since it is probably still too generic.
