### ISSUE TITLE
💎 Rename the heuristics column as heuristics_mine

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-data#50]
The `heuristics` column in the [cli/db-create.php](https://github.com/chesslablab/chess-data/blob/main/cli/db-create.php) script needs to be renamed as `heuristics_mine`.

**Comment by kristian0049** [comment]
I will take this issue.

**Comment by kristian0049** [comment]
I have made a pull request. Check it out when you can.

**Comment by programarivm** [comment]
@kristian0049 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

Happy coding!
