### ISSUE TITLE
🔄 Refactor ChessData\Cli\Seed\Users

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-data#53]
Probably it is not too clear what the classes suffixed with the word `Cli` in the [ChessData](https://github.com/chesslablab/chess-data/tree/main/src) namespace are for.

The thing is [ChessData\Cli\Seed\Users](https://github.com/chesslablab/chess-data/blob/main/cli/seed/users.php) is currently extending from [ChessData\PdoUserCli](https://github.com/chesslablab/chess-data/blob/main/src/PdoUserCli.php) but this is probably not necessary. A simpler solution is to implement `ChessData\Cli\Seed\Users` as the [ChessData\Cli\Mine\Heuristics](https://github.com/chesslablab/chess-data/blob/main/cli/mine/heuristics.php) class has been implemented in that `ChessData\Cli\Seed\Users` can be extended directly from `splitbrain\phpcli\CLI`.

`ChessData\Cli\Seed\Users` can be extended directly from `splitbrain\phpcli\CLI`.

Happy coding!

**Comment by kristian0049** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
See https://github.com/chesslablab/chess-data/issues/60
